import type { Metadata } from 'next';
import { Prompt } from 'next/font/google';

import styles from './ServiceLayout.module.css'; // Import the CSS module
import NavigationBar from '../../components/NavigationBar'

const inter = Prompt({weight: '400', subsets: ['thai']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function ServiceLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <body className={inter.className}>
        <div className={styles.layoutBackground}> 
            <div className={styles.contentWrapper}>
                <NavigationBar/>
                {children}
            </div>
        </div>
      </body>
  );
}
