import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Button from '@mui/material/Button';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function ServiceLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex-row'>
            <p>This is service layout</p>
            <Button variant="outlined">Logout</Button>
        </div>
        {children}
      </body>
    </html>
  )
}
