import styles from './AuthenticationLayout.module.css';
import type { Metadata } from 'next'
import { Prompt } from 'next/font/google'
import Button from '@mui/material/Button';

const inter = Prompt({weight: '400', subsets: ['thai']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function AuthenticationLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <body className={inter.className}>
        <div className={styles.layoutBackground}>
            {children}
        </div>
    </body>
  )
}
